---
- name: Mail server configuration
  hosts: mail
  remote_user: "{{ users.deployer.name }}"
  sudo: yes
  port: "{{ ssh.port }}"
  roles:
    - mail
  tasks:
    - name: Loaded configuration files by precedence
      debug: var=precedence
      tags: always
    - vars/default/all
    - [ "vars/all", "vars/null" ]
    - [ "vars/default/type/{{ server_mail }}", "vars/null" ]
    - [ "vars/type/{{ server_mail }}", "vars/null" ]
    - [ "vars/default/type/{{ server_backup }}", "vars/null" ]
    - [ "vars/type/{{ server_backup }}", "vars/null" ]
    - [ "vars/default/type/{{ server_db }}", "vars/null" ]
    - [ "vars/type/{{ server_db }}", "vars/null" ]
    - [ "vars/default/type/{{ server_web }}", "vars/null" ]
    - [ "vars/type/{{ server_web }}", "vars/null" ]
    - [ "vars/default/{{ env }}/{{ env }}", "vars/null" ]
    - [ "vars/{{ env }}/{{ env }}", "vars/null" ]
    - [ "vars/default/{{ env }}/{{ env }}_{{ server_mail }}", "vars/null" ]
    - [ "vars/{{ env }}/{{ env }}_{{ server_mail }}", "vars/null" ]
    - [ "vars/default/{{ env }}/{{ env }}_{{ server_backup }}", "vars/null" ]
    - [ "vars/{{ env }}/{{ env }}_{{ server_backup }}", "vars/null" ]
    - [ "vars/default/{{ env }}/{{ env }}_{{ server_db }}", "vars/null" ]
    - [ "vars/{{ env }}/{{ env }}_{{ server_db }}", "vars/null" ]
    - [ "vars/default/{{ env }}_{{ server_web }}", "vars/null" ]
    - [ "vars/{{ env }}/{{ env }}_{{ server_web }}", "vars/null" ]
