---
- name: Mail server configuration
  hosts: mail
  remote_user: "{{ users.deployer.name }}"
  sudo: yes
  port: "{{ ssh.port }}"
  roles:
    - mail
  tasks:
    - name: Loaded configuration files by precedence
      debug: var=precedence
      tags: always
  vars_files:
    - vars/all
    - [ "vars/type/{{ server_smtp }}", "vars/null" ]
    - [ "vars/type/{{ server_backup }}", "vars/null" ]
    - [ "vars/type/{{ server_db }}", "vars/null" ]
    - [ "vars/type/{{ server_web }}", "vars/null" ]
    - [ "vars/{{ env }}/{{ env }}", "vars/null" ]
    - [ "vars/{{ env }}/{{ env }}_{{ server_smtp }}", "vars/null" ]
    - [ "vars/{{ env }}/{{ env }}_{{ server_backup }}", "vars/null" ]
    - [ "vars/{{ env }}/{{ env }}_{{ server_db }}", "vars/null" ]
    - [ "vars/{{ env }}/{{ env }}_{{ server_web }}", "vars/null" ]
