---
- name: Playbook - Run web servers configuration
  hosts: web
  remote_user: "{{ users.deployer.name }}"
  sudo: yes
  port: "{{ ssh.port }}"
  roles:
    - web
  vars_prompt:
    - name: "letsgo"
      prompt: "\n\e[1;35mYou’re about to deploy web configuration to web servers. Please make sure:\n
      - You’ve run the playbooks \e[0;35minit.yml\e[1;35m and \e[0;35mplay-common.yml\e[1;35m .\n
      - You’ve created and added the needed web scripts in \e[0;35mfiles/scripts/*.sh\e[1;35m.\n
      - You’ve added the deployer SSH key to your github account.\n
      Note: SSH server keys may have changed, so make sure your local \e[0;35m~/.ssh/known_hosts\e[1;35m is up to date.\n
      If you’re ready, then let’s rock! \e[00m\n
      (Press CTRL+C to cancel or Enter to continue)"
  tasks:
    - name: Loaded configuration files by precedence
      debug: var=precedence
      tags: always
  vars_files:
    - vars/all
    - [ "vars/type/{{ server_mail }}", "vars/null" ]
    - [ "vars/type/{{ server_backup }}", "vars/null" ]
    - [ "vars/type/{{ server_db }}", "vars/null" ]
    - [ "vars/type/{{ server_web }}", "vars/null" ]
    - [ "vars/{{ env }}/{{ env }}", "vars/null" ]
    - [ "vars/{{ env }}/{{ env }}_{{ server_mail }}", "vars/null" ]
    - [ "vars/{{ env }}/{{ env }}_{{ server_backup }}", "vars/null" ]
    - [ "vars/{{ env }}/{{ env }}_{{ server_db }}", "vars/null" ]
    - [ "vars/{{ env }}/{{ env }}_{{ server_web }}", "vars/null" ]