---
- name: Install common configuration shared by all servers
  hosts: all
  user: "{{user_deploy.name}}"
  sudo: yes
  port: "{{ports.ssh}}"
  roles:
    - common
  vars_prompt:
    - name: "letsgo"
      prompt: "\n\e[1;35mYou're about to deploy common configuration to all servers.\n
      Before, please make sure you've run the playbook \e[0;35minit.yml\e[1;35m.\n
      Note: SSH server keys may have changed, so make sure your local \e[0;35m~/.ssh/known_hosts\e[1;35m is up to date.\n
      \e[4;35mIMPORTANT\e[0;35m\e[1;35m: use \e[0;35m--skip-tags=\"creates\"\e[1;35m if you've already run this installation once.\n
      If you're ready, then let's rock! \e[00m\n
      (Press CTRL+C to cancel or Enter to continue)"
    - name: "root_password"
      prompt: "Enter root password (used to share keys between backup users)"
      private: yes
      confirm: yes