---
- name: restart ssh
  service: name=ssh state=restarted

- name: restart firewall
  service: name=ferm state=restarted

- name: restart smartd
  service: name=smartd state=restarted

- name: restart fail2ban
  service: name=fail2ban state=restarted

- name: restart cron
  service: name=cron state=restarted

- name: restart mysql
  service: name=mysql state=restarted
  ignore_errors: yes
