---
- name: Backup - Copy save database script
  template: src=undefined/scripts/saveDatabase.sh.j2 dest="{{ script.path }}saveDatabase.sh" mode=0750 owner=root group={{ script.group }}

- name: Backup - Backup database every day, 6AM
  cron: name="Save database" hour="6" minute="0" job="{{ script.path }}saveDatabase.sh" user=root
  notify:
    - restart cron
