---
- name: SSL - Create autosigned certificate
  command: openssl req -nodes -newkey rsa:4096 -x509 -subj "/C={{ ssl.company.country_code }}/ST={{ ssl.company.country }}/L={{ ssl.company.location }}/O={{ ssl.company.name }}/CN={{ postfix.domain }}" -days 3650 -keyout /etc/ssl/private/autosigned.postfix.key -out /etc/ssl/certs/autosigned.postfix.crt

- name: SSL - Create DH configuration
  command: openssl dhparam -out dhparam.pem 2048

- name: SSL - Create DH file
  command: openssl genpkey -paramfile dhparam.pem -out /etc/ssl/private/postfix.dh

- name: SSL - Remove DH configuration file
  file: state=absent path=dhparam.pem

- name: SSL - Protect autosigned private key
  file: path=/etc/ssl/private/autosigned.postfix.key owner=root group={{ postfix.group }} mode=0640

- name: SSL - Protect DH file
  file: path=/etc/ssl/private/postfix.dh owner=root group={{ postfix.group }} mode=0640

- name: SSL - Set permission for autosigned public key
  file: path=/etc/ssl/certs/autosigned.postfix.crt owner=root group={{ postfix.group }} mode=0644