#
# SSL for applications, copy or generate certificates, permissions
# @Tag ssl
#
---
- name: SSL - Install ssl | update repositories
  apt: update_cache=yes upgrade=safe state=latest

- name: SSL - Install ssl
  apt: name={{ item }} state=present update_cache=yes force=yes
  with_items:
    - openssl
    - openssl-blacklist
    - openssl-blacklist-extra

- name: SSL - Copy applications private keys
  copy: src=files/ssl/private/{{ item.short_name }}.key dest=/etc/ssl/private/{{ item.short_name }}.key mode=0640 owner=root group=www-data
  when: item.url is defined and (applications.enabled or adminer.enabled) and not item.autosigned
  with_flattened:
    - applications.sites | default({})
    - "{{ [adminer] }}"

- name: SSL - Copy Ca certificates
  copy: src=files/ssl/ca/{{ item.short_name }}.cabundle dest=/etc/ssl/certs/{{ item.short_name }}.cabundle mode=0644 owner=root group=www-data
  when: item.url is defined and (applications.enabled or adminer.enabled) and not item.autosigned
  with_flattened:
    - applications.sites | default({})
    - "{{ [adminer] }}"

- name: SSL - Copy application certificates
  copy: src=files/ssl/certs/{{ item.short_name }}.crt dest=/etc/ssl/certs/{{ item.short_name }}.crt mode=0644 owner=root group=www-data
  when: item.url is defined and (applications.enabled or adminer.enabled) and not item.autosigned
  with_flattened:
    - applications.sites | default({})
    - "{{ [adminer] }}"

- name: SSL - Create local CA certificate
  command: openssl req -nodes -newkey rsa:4096 -x509 -subj "/C={{ ssl.company.country_code }}/ST={{ ssl.company.country }}/L={{ ssl.company.location }}/O={{ ssl.company.name }}/CN={{ ssl.company.domain }}" -days 3650 -keyout /etc/ssl/private/ca.{{ item.short_name }}.key -out /etc/ssl/certs/ca.{{ item.short_name }}.crt
  when: item.url is defined and (applications.enabled or adminer.enabled) and item.autosigned
  with_flattened:
    - applications.sites | default({})
    - "{{ [adminer] }}"
  tags:
    - renew

- name: SSL - Protect local CA private key
  file: path=/etc/ssl/private/ca.{{ item.short_name }}.key owner=root group=root mode=0640
  when: item.url is defined and (applications.enabled or adminer.enabled) and item.autosigned
  with_flattened:
    - applications.sites | default({})
    - "{{ [adminer] }}"
  tags:
    - renew

- name: SSL - Set local CA permissions
  file: path=/etc/ssl/certs/ca.{{ item.short_name }}.crt owner=root group=www-data mode=0644
  when: item.url is defined and (applications.enabled or adminer.enabled) and item.autosigned
  with_flattened:
    - applications.sites | default({})
    - "{{ [adminer] }}"
  tags:
    - renew

- name: SSL - Create needed local keys
  command: openssl genrsa -out /etc/ssl/private/autosigned.{{ item.short_name }}.key 4096
  when: item.url is defined and (applications.enabled or adminer.enabled) and item.autosigned
  with_flattened:
    - applications.sites | default({})
    - "{{ [adminer] }}"
  tags:
    - renew

- name: SSL - Create needed certificate requests
  command: openssl req -new -key /etc/ssl/private/autosigned.{{ item.short_name }}.key -out /etc/ssl/certs/autosigned.{{ item.short_name }}.csr -subj "/C={{ ssl.company.country_code }}/ST={{ ssl.company.country }}/L={{ ssl.company.location }}/O={{ ssl.company.name }}/CN={{ item.url }}"
  when: item.url is defined and (applications.enabled or adminer.enabled) and item.autosigned
  with_flattened:
    - applications.sites | default({})
    - "{{ [adminer] }}"
  tags:
    - renew

- name: SSL - Sign certificates
  command: openssl x509 -req -in /etc/ssl/certs/autosigned.{{ item.short_name }}.csr -CA /etc/ssl/certs/ca.{{ item.short_name }}.crt -CAkey /etc/ssl/private/ca.{{ item.short_name }}.key -CAcreateserial -out /etc/ssl/certs/autosigned.{{ item.short_name }}.crt -days 3650
  when: item.url is defined and (applications.enabled or adminer.enabled) and item.autosigned
  with_flattened:
    - applications.sites | default({})
    - "{{ [adminer] }}"
  tags:
    - renew
  notify:
    - restart apache2

- name: SSL - Delete certificate requests files
  file: state=absent path=/etc/ssl/certs/autosigned.{{ item.short_name }}.csr
  with_flattened:
    - applications.sites | default({})
    - "{{ [adminer] }}"
  tags:
    - renew

- name: SSL - Protect autosigned private key
  file: path=/etc/ssl/private/autosigned.{{ item.short_name }}.key owner=root group=www-data mode=0640
  when: item.url is defined and (applications.enabled or adminer.enabled) and item.autosigned
  with_flattened:
    - applications.sites | default({})
    - "{{ [adminer] }}"
  tags:
    - renew

- name: SSL - Set permission for autosigned public key
  file: path=/etc/ssl/certs/autosigned.{{ item.short_name }}.crt owner=root group=www-data mode=0644
  when: item.url is defined and (applications.enabled or adminer.enabled) and item.autosigned
  with_flattened:
    - applications.sites | default({})
    - "{{ [adminer] }}"
  tags:
    - renew
