---
- name: Fail2ban - Install fail2ban | update repositories
  apt: update_cache=yes upgrade=safe state=latest

- name: Fail2ban - Install fail2ban
  apt: name={{ item }} state=present
  with_items:
    - fail2ban
    - gamin

- name: Fail2ban - Replace by the specific configuation file
  template: src=etc/fail2ban/jail.conf.j2 dest=/etc/fail2ban/jail.conf owner=root group=root mode=0644 backup=yes
  notify:
    - restart fail2ban
