---
- include: check.yml tags=always

- include: time.yml tags=time

- include: packages.yml tags=packages
  when: package.enabled

- include: scripts.yml tags=scripts
  when: script.enabled

- include: sharedgroup.yml tags=sharedgroup
  when: shared_group.enabled

- include: ssh.yml tags=ssh
  when: ssh.enabled

- include: users.yml tags=users

- include: motd.yml tags=motd
  when: motd.enabled

- include: backup.yml tags=backup
  when: backup.enabled and ssh.enabled and script.enabled

- include: smartd.yml tags=smartd
  when: smartd.enabled

- include: fail2ban.yml tags=fail2ban
  when: failtoban.enabled

- include: firewall.yml tags=firewall
  when: firewall.enabled

- include: ruby.yml tags=ruby
  when: ruby.enabled

- include: npm.yml tags=npm
  when: npm.enabled

- include: ssl.yml tags=ssl
  when: ssl.enabled and mariadb.enabled