---
- name: Packages - Update & upgrade servers with APT
  apt: update_cache=yes upgrade=safe state=latest

- name: Packages - Install common packages
  apt: name={{ item }} state=present
  with_items:
    - sudo
    - sshpass
    - zsh
    - vim
    - htop
    - openssl
    - openssh-blacklist
    - openssh-blacklist-extra
    - python-pycurl
    - fail2ban
    - smartmontools
    - ferm
    - gamin
