---
- name: Packages - Update & upgrade servers
  apt: update_cache=yes upgrade=safe state=latest

- name: Packages - Install common packages
  apt: name={{ item }} state=present
  with_items: package.packages
