#
# SCRIPT basic configuration
# Gzts everything in files/scripts/ and move it to the corresponding server
# @Todo Every server-related scripts should be moved to corresponding role
#
---
- name: Script - Create group for script
  group: name={{ script.group }} state=present system=yes

- name: Script - Create log directory
  file: state=directory owner=root group={{ script.group }} mode=2770 path={{ script.logpath }}

- name: Script - Create logrotate configuration file for script logs
  template: src=etc/logrotate.d/scripts.j2 dest=/etc/logrotate.d/scripts owner=root group=root mode=0644

- name: Script - Create script directory
  file: state=directory owner=root group=root mode=0755 path={{ script.path }}

- name: Script - Copy init script
  template: src=undefined/scripts/init.sh.j2 dest="{{ script.path }}init.sh" mode=0755 owner=root group={{ script.group }}

- name: Script - Copy global constants script
  template: src=undefined/scripts/globalConstants.sh.j2 dest="{{ script.path }}globalConstants.sh" mode=0755 owner=root group={{ script.group }}

- name: Script - Copy update script
  template: src=undefined/scripts/aptUpdate.sh.j2 dest="{{ script.path }}aptUpdate.sh" mode=0750 owner=root group={{ script.group }}

- name: Backup - Set cron for updating apt, every day 6:15AM
  cron: name="Update apt" hour="6" minute="15" job="{{ script.path }}aptUpdate.sh" user=root
  notify:
    - restart cron

- name: Scripts - Copy general scripts
  copy: src={{ item }} dest={{ script.path }} mode=0750 owner=root group={{ script.group }}
  with_fileglob:
    - "../../../files/scripts/*.sh"

- name: Scripts - Copy environment scripts
  copy: src={{ item }} dest={{ script.path }} mode=0750 owner=root group={{ script.group }}
  with_fileglob:
    - "../../../files/scripts/{{ env }}/*.sh"

- name: Scripts - Copy backup environment scripts
  copy: src={{ item }} dest={{ script.path }} mode=0750 owner=root group={{ script.group }}
  with_fileglob:
    - "../../../files/scripts/{{ env }}/backup/*.sh"
  when: inventory_hostname in groups['backup']

- name: Scripts - Copy mail environment scripts
  copy: src={{ item }} dest={{ script.path }} mode=0750 owner=root group={{ script.group }}
  with_fileglob:
    - "../../../files/scripts/{{ env }}/mail/*.sh"
  when: inventory_hostname in groups['mail']

- name: Scripts - Copy web environment scripts
  copy: src={{ item }} dest={{ script.path }} mode=0750 owner=root group={{ script.group }}
  with_fileglob:
    - "../../../files/scripts/{{ env }}/web/*.sh"
  when: inventory_hostname in groups['web']

- name: Scripts - Copy db environment scripts
  copy: src={{ item }} dest={{ script.path }} mode=0750 owner=root group={{ script.group }}
  with_fileglob:
    - "../../../files/scripts/{{ env }}/db/*.sh"
  when: inventory_hostname in groups['db']/
