---
- name: Init - Update & upgrade servers
  apt: update_cache=yes upgrade=safe state=latest

- name: Init - Install sudo
  apt: name=sudo state=present

- name: Init - Create user deploy
  user: name={{ users.deployer.name }} state=present groups=sudo password="{{ user_deploy_password }}" update_password=on_create generate_ssh_key=yes ssh_key_bits=4096

- name: Init - Set SSH keys for user deploy
  authorized_key: user={{ users.deployer.name }} key="{{ lookup('file', '../../../files/sshkeys/'+ users.deployer.name +'.pub') }}"

- name: Init - Change SSH default port
  lineinfile: dest=/etc/ssh/sshd_config regexp="^#?\s*Port\s*" line="Port {{ ssh.port }}" backup=yes owner=root mode=0644 validate='/usr/sbin/sshd -T -f %s'
  notify:
    - restart ssh
